services:
  geolearn.api:
    image: geolearn.api
    build:
      context: .
      dockerfile: GeoLearn.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=geolearn;Username=app;Password=geolearnht2024
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=geolearn
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=geolearnht2024
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - geolearn.api

volumes:
  postgres_data: